# Generated by Django 3.1.14 on 2022-05-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220503_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
