# Generated by Django 3.1.14 on 2022-05-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220503_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(default='JASKD42', max_length=7),
            preserve_default=False,
        ),
    ]
