# Generated by Django 3.1.14 on 2022-05-05 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_referral_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['points']},
        ),
    ]
