# Generated by Django 3.1.14 on 2022-05-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220505_0549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-points']},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
