# Generated by Django 3.1.14 on 2022-05-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20220506_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
